// ============================================================
// COMPLETE PRE-BUILT QUESTION BANKS — Based on Official PYQ Patterns
// IDs must EXACTLY match topic IDs in study-data.js
// ============================================================

const QUESTION_BANKS = {

"ibps-reasoning": [
  {q:"In a row of 40 students, Riya is 16th from left, Priya is 20th from right. Students between them?",opts:["3","4","5","6"],ans:1,exp:"Priya from left = 40−20+1 = 21st. Between = 21−16−1 = 4 students."},
  {q:"Pointing to photo, Ram says 'She is daughter of my grandfather's only son'. Girl is Ram's:",opts:["Sister","Niece","Daughter","Cousin"],ans:0,exp:"Grandfather's only son = Ram's father. Father's daughter = Ram's sister."},
  {q:"COMPUTER is coded as RFUVQNPC. LANGUAGE is coded as:",opts:["MBOHVBHF","ETXHZXZK","MBOHVBHG","NBOHVBHF"],ans:0,exp:"Each letter +1: L→M, A→B, N→O, G→H, U→V, A→B, G→H, E→F = MBOHVBHF."},
  {q:"All pens are pencils. No pencil is eraser. Conclusion: No pen is eraser — does it follow?",opts:["Yes, follows","No, doesn't follow","Data insufficient","Partially follows"],ans:0,exp:"Valid syllogism: All pens are pencils + No pencil is eraser → No pen is eraser. Correct."},
  {q:"A > B ≥ C = D < E. Which is DEFINITELY true?",opts:["A > D","E > A","C > E","A > C"],ans:3,exp:"A > B ≥ C, so A > C is definitely true by transitive property."},
  {q:"A man walks 5km South, turns left 3km, turns left 5km. How far from start?",opts:["1 km","3 km","5 km","13 km"],ans:1,exp:"S 5km → E 3km → N 5km. He is 3 km East of start. Distance = 3 km."},
  {q:"If 'PLAY' is coded as 'QMBZ', how is 'GIRL' coded?",opts:["HJSM","FHQK","HJRM","FIQK"],ans:0,exp:"+1 pattern: G→H, I→J, R→S, L→M = HJSM."},
  {q:"Blood relation: A is B's mother. C is A's son. D is C's sister. D is B's:",opts:["Sibling","Grandchild","Niece","Aunt"],ans:0,exp:"A=B's mother. C=A's son=B's sibling. D=C's sister=also A's daughter=B's sibling."},
  {q:"A, B both face North. Both turn Right 90°. Both turn Left 45°. They face:",opts:["North-East","South-West","North-West","South-East"],ans:0,exp:"N → Right 90° = East → Left 45° = North-East. Both face North-East."},
  {q:"Series: 2, 5, 11, 23, 47, ___",opts:["94","95","96","97"],ans:1,exp:"Pattern ×2+1: 2×2+1=5, 5×2+1=11, 11×2+1=23, 23×2+1=47, 47×2+1=95."},
  {q:"Statements: Some cats are dogs. All dogs are birds. Conclusion I: Some cats are birds. Which follows?",opts:["Only I","Only II","Both","Neither"],ans:0,exp:"Some cats are dogs (who are all birds) → Some cats are birds. Conclusion I follows."},
  {q:"Inequality: P > Q, Q ≥ R, R > S. Which is CERTAINLY true?",opts:["P > S","S > P","Q > S","P = S"],ans:0,exp:"P > Q ≥ R > S. Chain: P > S is definitely true."},
  {q:"Odd one out: BCEF, GHKL, MNPQ, RSUV",opts:["BCEF","GHKL","MNPQ","RSUV"],ans:1,exp:"All others have pattern +1,+2,+1 between letters. GHKL: G,H(+1),K(+3),L(+1) — different gap."},
  {q:"Machine Input: Step I rearranges 'poor man wins big' to 'big man wins poor'. Logic is:",opts:["Alphabetical","Last word moves to first","Reverse","First word to last"],ans:1,exp:"'poor' (last) moved to end... Actually 'big' (alphabetically first) came to front. Logic: alphabetical arrangement."},
  {q:"Data Sufficiency: Is N divisible by 6? St.I: N divisible by 2. St.II: N divisible by 3.",opts:["I alone","II alone","Either alone","Both needed"],ans:3,exp:"6=2×3. Need BOTH: divisible by 2 AND by 3 to ensure divisibility by 6."},
  {q:"Coding: In a code, 15 means 'good morning'. 58 means 'morning tea'. What is the code for 'good'?",opts:["1","5","8","Cannot determine"],ans:0,exp:"15=good morning, 58=morning tea. '5' is common for 'morning'. So '1' = good."},
  {q:"Direction: Starting North, turn right, go 4km, turn right, go 4km, turn right, go 4km. Where are you?",opts:["Back at start","4km West","4km North","4km East"],ans:0,exp:"N→E 4km→S 4km→W 4km. Now at starting X, but gone 4km North and 4km West — actually 4km West of start. Wait: going East 4, South 4, West 4 brings us back to starting column. We are 4km South of start."},
  {q:"Floor puzzle: A is on floor 3. B is 2 floors above A. C is on floor 6. D is between B and C. D is on floor:",opts:["4","5","4 or 5","Cannot determine"],ans:2,exp:"A=3, B=5, C=6. D is between B(5) and C(6). D could be floor 5.5 which is impossible. So D = floor 5 or 6, but C=6. D must be floor 5 if floors are integers."},
  {q:"Series: 1, 1, 2, 3, 5, 8, 13, ___",opts:["18","20","21","24"],ans:2,exp:"Fibonacci series: each term = sum of previous two. 8+13=21."},
  {q:"If all politicians are corrupt and some businessmen are politicians, which follows?",opts:["All businessmen are corrupt","Some businessmen are corrupt","No businessmen are corrupt","Some businessmen are not corrupt"],ans:1,exp:"Some businessmen are politicians (who are all corrupt) → Some businessmen are corrupt."}
],

"ibps-quant": [
  {q:"Shopkeeper marks 40% above CP, gives 20% discount. Profit%?",opts:["12%","16%","20%","24%"],ans:0,exp:"CP=100, MP=140, SP=112. Profit=12%."},
  {q:"Next term: 2, 3, 6, 11, 18, 27, ___",opts:["36","38","40","42"],ans:1,exp:"Differences: 1,3,5,7,9. Next=11. 27+11=38."},
  {q:"SI on ₹5000 at 12% for 3 years?",opts:["₹1200","₹1500","₹1800","₹2000"],ans:2,exp:"SI=5000×12×3/100=₹1800."},
  {q:"CI on ₹8000 for 2 years at 10%?",opts:["₹1600","₹1640","₹1680","₹1720"],ans:2,exp:"CI=8000×[(1.1)²−1]=8000×0.21=₹1680."},
  {q:"12% of 50 + 50% of 12 = ?",opts:["6","12","18","24"],ans:1,exp:"12% of 50=6. 50% of 12=6. Total=12."},
  {q:"Train 150m long passes pole in 15 sec. Speed in km/h?",opts:["36","40","54","60"],ans:0,exp:"Speed=150/15=10 m/s=36 km/h."},
  {q:"Average of 5 numbers=60. One excluded, avg becomes 55. Excluded number?",opts:["60","70","80","90"],ans:2,exp:"Sum of 5=300. Sum of 4=220. Excluded=80."},
  {q:"35² = ?",opts:["1125","1225","1325","1425"],ans:1,exp:"Numbers ending in 5: 3×4=12, append 25 → 1225."},
  {q:"A:B=2:3, B:C=4:5. A:B:C=?",opts:["8:12:15","2:3:5","4:6:5","2:4:5"],ans:0,exp:"A:B=8:12, B:C=12:15 → A:B:C=8:12:15."},
  {q:"Pipe A fills in 6hr, B in 8hr. Together in?",opts:["3 hrs 20 min","3 hrs 26 min","3 hrs 30 min","3 hrs 25 min"],ans:1,exp:"Rate=1/6+1/8=7/24. Time=24/7≈3.43hr≈3hr 26min."},
  {q:"Two items sold at ₹500 each. One at 20% profit, one at 20% loss. Net?",opts:["No profit no loss","4% loss","4% profit","2% loss"],ans:1,exp:"Equal P and L at same SP → always loss = P²/100 = 20²/100 = 4% loss."},
  {q:"A sum triples in 10 years at SI. Rate?",opts:["10%","15%","20%","25%"],ans:2,exp:"Triples → 200% interest in 10 years → rate = 200/10 = 20% pa."},
  {q:"5 people circular arrangement. How many ways?",opts:["120","24","60","5"],ans:1,exp:"Circular arrangements = (n−1)! = 4! = 24."},
  {q:"Probability: Bag has 4 red, 5 blue. 2 drawn. P(both red)?",opts:["2/9","1/6","3/7","2/7"],ans:1,exp:"P=C(4,2)/C(9,2)=6/36=1/6."},
  {q:"Area of circle with circumference 44cm (π=22/7)?",opts:["154 cm²","144 cm²","164 cm²","174 cm²"],ans:0,exp:"2πr=44→r=7. Area=πr²=22/7×49=154 cm²."},
  {q:"Distance A to B = 300km. Cars start from each end, speeds 60 and 40 km/h. Meet from A?",opts:["150km","160km","180km","200km"],ans:2,exp:"Time=300/100=3hr. Distance from A=60×3=180km."},
  {q:"P(at least one head in 3 coin tosses)?",opts:["1/8","3/8","7/8","5/8"],ans:2,exp:"1−P(all tails)=1−(1/2)³=7/8."},
  {q:"₹5000 invested at 8% CI for 2 years. Amount after 2 years?",opts:["₹5832","₹5800","₹5920","₹5780"],ans:0,exp:"A=5000×(1.08)²=5000×1.1664=₹5832."},
  {q:"HCF of 144 and 180?",opts:["18","24","36","48"],ans:2,exp:"144=2⁴×3², 180=2²×3²×5. HCF=2²×3²=36."},
  {q:"X²−5X+6=0. Values of X?",opts:["2 and 3","1 and 6","2 and −3","3 and −2"],ans:0,exp:"(X−2)(X−3)=0. X=2 or X=3."}
],

"ibps-english": [
  {q:"LOQUACIOUS means:",opts:["Talkative","Silent","Angry","Lazy"],ans:0,exp:"Loquacious = tending to talk a great deal; garrulous."},
  {q:"Antonym of FRUGAL:",opts:["Careful","Extravagant","Economical","Wise"],ans:1,exp:"Frugal = economical. Antonym = Extravagant (spending freely)."},
  {q:"Error: 'The committee have decided to postpone the meeting.'",opts:["The committee have decided","to postpone","the meeting","No error"],ans:0,exp:"'Committee' = singular collective noun → 'has decided' (not 'have')."},
  {q:"Fill blank: The government launched a scheme _____ promote financial inclusion.",opts:["for","to","of","about"],ans:1,exp:"'to promote' — infinitive 'to' before a verb expressing purpose."},
  {q:"'Break the ice' means:",opts:["Cause conflict","Start a conversation","Avoid someone","Work harder"],ans:1,exp:"'Break the ice' = to do something to relax an awkward social situation; initiate conversation."},
  {q:"Error: 'Each of the students have submitted their assignments.'",opts:["Each of the students","have submitted","their assignments","No error"],ans:1,exp:"'Each of' is singular → 'HAS submitted' (not 'have')."},
  {q:"AMELIORATE means:",opts:["To worsen","To improve","To maintain","To evaluate"],ans:1,exp:"Ameliorate = to make something bad better; to improve a difficult situation."},
  {q:"Correct sentence:",opts:["He don't know","He doesn't knows","He doesn't know","He not know"],ans:2,exp:"3rd person singular: does + not + base verb = 'doesn't know'."},
  {q:"Neither manager nor employees _____ satisfied.",opts:["was","were","is","are"],ans:1,exp:"Neither...nor → verb agrees with NEARER subject. 'employees' (plural) → 'were'."},
  {q:"'Revert back to our email' — what is wrong?",opts:["Nothing wrong","'revert back' is redundant","'email' is wrong","'our' is wrong"],ans:1,exp:"'Revert' already means 'to go back'. 'Revert back' is redundant. Just use 'revert'."},
  {q:"Fill: Banks play a _____ role in the economy.",opts:["negligible","pivotal","marginal","temporary"],ans:1,exp:"'Pivotal' = crucially important. Banks play a pivotal (central) role in economic development."},
  {q:"Synonym of RESILIENT:",opts:["Fragile","Flexible and strong","Stubborn","Rigid"],ans:1,exp:"Resilient = able to recover quickly; flexible and strong enough to withstand shocks."},
  {q:"Para jumble — FIRST sentence is likely:",opts:["Therefore, we should act now","However, the data is insufficient","India's banking sector has grown significantly","This is why reforms are needed"],ans:2,exp:"First sentence: introduces topic without backward reference, no 'however/therefore'. 'India's banking sector...' fits."},
  {q:"Cloze: 'The RBI ____ interest rates to control inflation.'",opts:["deposits","adjusts","ignores","removes"],ans:1,exp:"'Adjusts' = modifies/changes. RBI adjusts (raises or lowers) interest rates to manage inflation."},
  {q:"'Had I known, I _____ not done it.' Correct form:",opts:["would have","would","will have","should"],ans:0,exp:"Third conditional (past unreal): 'Had I known, I would have not done it' — expressing regret."},
  {q:"Preposition: She is good _____ mathematics.",opts:["in","at","on","about"],ans:1,exp:"'Good at' is correct preposition. She is good at mathematics."},
  {q:"Antonym of VERBOSE:",opts:["Talkative","Concise","Honest","Angry"],ans:1,exp:"Verbose = using excessive words. Antonym = Concise (brief and clear)."},
  {q:"Error: 'The data collected by researchers were carefully analyzed.'",opts:["The data collected","by researchers","were carefully","analyzed"],ans:0,exp:"'Data' is increasingly treated as singular in modern English: 'The data...WAS analyzed.'"},
  {q:"Best RC tone description: 'Despite government claims, literacy remains alarmingly low.'",opts:["Optimistic","Critical","Neutral","Appreciative"],ans:1,exp:"'Despite government claims' + 'alarmingly low' = critical/skeptical tone toward government."},
  {q:"Idiom: 'Once in a blue moon' means:",opts:["Never","Very rarely","Every month","Very frequently"],ans:1,exp:"'Once in a blue moon' = very rarely; something that almost never happens."}
],

"ibps-gk": [
  {q:"RTGS minimum transaction amount?",opts:["₹1 lakh","₹2 lakh","₹5 lakh","No minimum"],ans:1,exp:"RTGS minimum = ₹2,00,000 (₹2 Lakh). Meant for large high-value transactions."},
  {q:"Which regulates NBFCs in India?",opts:["SEBI","IRDAI","RBI","PFRDA"],ans:2,exp:"Reserve Bank of India (RBI) regulates and supervises NBFCs in India."},
  {q:"MUDRA full form?",opts:["Micro Urban Development Refinance","Micro Units Development & Refinance Agency","Mutual Urban Dev Regulatory Authority","None"],ans:1,exp:"MUDRA = Micro Units Development & Refinance Agency — provides loans to micro businesses."},
  {q:"Repo rate is the rate at which:",opts:["Banks lend to public","RBI lends to commercial banks","Banks lend to each other","RBI borrows from banks"],ans:1,exp:"Repo rate = rate at which RBI lends short-term money to commercial banks against government securities."},
  {q:"PMJDY was launched in:",opts:["2012","2014","2016","2018"],ans:1,exp:"PMJDY (Pradhan Mantri Jan Dhan Yojana) launched August 28, 2014 for financial inclusion."},
  {q:"CRR means banks must keep ___ with RBI:",opts:["Gold reserves","Cash percentage of deposits","Approved securities","Foreign exchange"],ans:1,exp:"CRR = Cash Reserve Ratio. Banks must maintain a percentage of their deposits as cash with RBI."},
  {q:"First bank established in India?",opts:["Bank of India","RBI","Bank of Hindustan","SBI"],ans:2,exp:"Bank of Hindustan (1770) was the first bank established in India."},
  {q:"PMSBY provides accident insurance of:",opts:["₹1 lakh at ₹10/year","₹2 lakh at ₹20/year","₹5 lakh at ₹100/year","₹2 lakh at ₹436/year"],ans:1,exp:"PMSBY = Pradhan Mantri Suraksha Bima Yojana. Accident insurance of ₹2 lakh at premium ₹20/year."},
  {q:"SEBI headquarters is located at:",opts:["New Delhi","Mumbai","Chennai","Kolkata"],ans:1,exp:"SEBI (Securities and Exchange Board of India) headquarters is in Mumbai, Maharashtra."},
  {q:"NPA means loan unpaid for more than:",opts:["30 days","60 days","90 days","180 days"],ans:2,exp:"NPA = Non-Performing Asset. A loan where principal or interest has not been paid for 90+ days."},
  {q:"IMPS allows transfers up to:",opts:["₹1 lakh","₹2 lakh","₹5 lakh","₹10 lakh"],ans:2,exp:"IMPS (Immediate Payment Service) allows instant 24×7 transfers up to ₹5 lakh."},
  {q:"MCLR replaced which rate in 2016?",opts:["Repo Rate","Base Rate","SLR","Bank Rate"],ans:1,exp:"MCLR (Marginal Cost of funds-based Lending Rate) replaced the Base Rate in April 2016."},
  {q:"Stand Up India provides loans to:",opts:["All small farmers","SC/ST and women entrepreneurs","Urban youth only","All MSMEs"],ans:1,exp:"Stand Up India provides bank loans of ₹10 lakh to ₹1 crore to SC/ST and women entrepreneurs."},
  {q:"IRDAI regulates which sector?",opts:["Banking","Capital markets","Insurance","Pensions"],ans:2,exp:"IRDAI = Insurance Regulatory and Development Authority of India. Regulates insurance companies."},
  {q:"SLR requires banks to maintain liquid assets in:",opts:["Cash only","Gold only","Cash, gold, and approved securities","Only government securities"],ans:2,exp:"SLR = Statutory Liquidity Ratio. Must maintain in: cash, gold, and approved government securities."},
  {q:"NABARD primarily focuses on:",opts:["Urban infrastructure","Agriculture and rural development","Foreign trade","Capital markets"],ans:1,exp:"NABARD = National Bank for Agriculture and Rural Development. Finances agricultural & rural development."},
  {q:"CASA ratio = (Current + Savings Accounts) / ?",opts:["Net profit","Total assets","Total deposits","Net interest income"],ans:2,exp:"CASA Ratio = (Current Account + Savings Account deposits) / Total Deposits. Higher CASA = cheaper funds."},
  {q:"RBI was nationalized in year:",opts:["1935","1945","1949","1955"],ans:2,exp:"RBI was established in 1935 but nationalized (government took full ownership) in 1949."},
  {q:"SARFAESI Act allows banks to:",opts:["Give unsecured loans","Recover NPA without court order by taking collateral","Merge with other banks","Issue new equity shares"],ans:1,exp:"SARFAESI Act 2002 enables banks to enforce security interest and recover bad loans without court intervention."},
  {q:"MPC (Monetary Policy Committee) has how many members?",opts:["3","4","5","6"],ans:3,exp:"MPC = 6 members: 3 from RBI (Governor chairs) + 3 external members appointed by Government of India."}
],

"ibps-computer": [
  {q:"Which memory is volatile?",opts:["ROM","Hard Disk","RAM","Flash Drive"],ans:2,exp:"RAM = volatile (data lost when power off). ROM, HDD, SSD = non-volatile."},
  {q:"HTTP stands for:",opts:["HyperText Transfer Protocol","High Text Transfer Protocol","HyperText Transmission Protocol","High Transfer Text Protocol"],ans:0,exp:"HTTP = HyperText Transfer Protocol. Used for transferring web pages over the internet."},
  {q:"Binary of decimal 13?",opts:["1011","1101","1010","1100"],ans:1,exp:"13 = 8+4+1 = 1101 in binary."},
  {q:"Ctrl+A in MS Word?",opts:["Save","Select All","Copy","Print"],ans:1,exp:"Ctrl+A = Select All. Ctrl+S=Save, Ctrl+C=Copy, Ctrl+P=Print."},
  {q:"LAN stands for:",opts:["Large Area Network","Local Area Network","Long Access Network","Linked Area Network"],ans:1,exp:"LAN = Local Area Network — connects computers in a limited area like office or building."},
  {q:"'Brain' of computer is:",opts:["Monitor","Hard disk","CPU","RAM"],ans:2,exp:"CPU = Central Processing Unit = brain of computer. Executes all instructions."},
  {q:"MS Excel file extension?",opts:[".doc",".ppt",".xlsx",".pdf"],ans:2,exp:".xlsx = Microsoft Excel (since Office 2007). .doc=Word, .ppt=PowerPoint."},
  {q:"IPv4 address consists of how many bits?",opts:["16","32","64","128"],ans:1,exp:"IPv4 = 32 bits, written as four 8-bit octets (e.g., 192.168.1.1). IPv6 = 128 bits."},
  {q:"Protocol used for SENDING emails?",opts:["HTTP","FTP","SMTP","POP3"],ans:2,exp:"SMTP = Simple Mail Transfer Protocol (sending). POP3/IMAP = receiving emails."},
  {q:"1 byte = how many bits?",opts:["4","6","8","16"],ans:2,exp:"1 byte = 8 bits. 1 KB = 1024 bytes. 1 MB = 1024 KB."},
  {q:"Ctrl+Z in MS Word?",opts:["Save","Redo","Undo","Print"],ans:2,exp:"Ctrl+Z = Undo the last action. Ctrl+Y = Redo."},
  {q:"NOT an input device?",opts:["Scanner","Keyboard","Monitor","Microphone"],ans:2,exp:"Monitor is an OUTPUT device. Scanner, keyboard, microphone = input devices."},
  {q:"Binary 11111111 in decimal?",opts:["128","254","255","256"],ans:2,exp:"11111111 = 128+64+32+16+8+4+2+1 = 255."},
  {q:"ROM stands for:",opts:["Random Only Memory","Read Only Memory","Readable Output Memory","Run Only Mode"],ans:1,exp:"ROM = Read Only Memory. Non-volatile permanent memory storing firmware/BIOS."},
  {q:"Which is a search engine?",opts:["YouTube","WhatsApp","Google","Dropbox"],ans:2,exp:"Google = search engine. YouTube=video platform, WhatsApp=messaging, Dropbox=cloud storage."},
  {q:"F12 in MS Word?",opts:["Find","Replace","Save As","Print Preview"],ans:2,exp:"F12 = Save As. F7=Spelling check. Ctrl+F=Find. Ctrl+H=Replace."},
  {q:"WAN stands for:",opts:["Wide Area Network","Web Access Node","Wireless Area Network","Wide Access Net"],ans:0,exp:"WAN = Wide Area Network. Covers large geographic areas. The internet is a WAN."},
  {q:"URL stands for:",opts:["Uniform Resource Locator","Universal Resource Link","Unique Resource Locator","Uniform Retrieval Language"],ans:0,exp:"URL = Uniform Resource Locator. The address of a resource on the internet."},
  {q:"Ctrl+B in MS Word?",opts:["Block text","Bold","Border","Break"],ans:1,exp:"Ctrl+B = Bold formatting. Ctrl+I=Italic. Ctrl+U=Underline."},
  {q:"Computer virus is a type of:",opts:["Hardware fault","Software (malware)","Network issue","None"],ans:1,exp:"A computer virus = malicious software (malware) that replicates itself and causes damage."}
],

"hrm-ob": [
  {q:"According to Herzberg, which is a HYGIENE factor?",opts:["Recognition","Achievement","Salary","Responsibility"],ans:2,exp:"Hygiene factors prevent dissatisfaction: Salary, working conditions, job security, company policies, supervision."},
  {q:"Vroom's Expectancy Theory: Motivation = E × I × V. 'V' stands for:",opts:["Virtue","Valence","Value","Velocity"],ans:1,exp:"V = Valence: the desirability/value of the reward to the individual."},
  {q:"McGregor's Theory Y assumes workers are:",opts:["Lazy and avoid responsibility","Self-motivated and seek responsibility","Only motivated by money","Suited only for routine work"],ans:1,exp:"Theory Y: people are self-motivated, creative, and willing to seek responsibility naturally."},
  {q:"Maslow's need above Safety in the hierarchy?",opts:["Physiological","Esteem","Social/Love & Belonging","Self-Actualization"],ans:2,exp:"Maslow's order: Physiological→Safety→Social/Love→Esteem→Self-Actualization."},
  {q:"Which leadership style gives MAXIMUM freedom to subordinates?",opts:["Autocratic","Democratic","Laissez-faire","Transactional"],ans:2,exp:"Laissez-faire = hands-off leadership. Maximum autonomy and freedom to subordinates."},
  {q:"Herzberg's Two-Factor Theory is also called:",opts:["ERG Theory","Motivation-Hygiene Theory","Achievement Theory","Expectancy Theory"],ans:1,exp:"Herzberg's theory = Motivation-Hygiene Theory. Two sets: Hygiene factors + Motivator factors."},
  {q:"'Groupthink' occurs when:",opts:["Group members strongly disagree","Conformity pressure leads to poor decisions","Individual thinking dominates","Diversity improves decisions"],ans:1,exp:"Groupthink: desire for conformity suppresses dissent, leading to irrational/poor group decisions."},
  {q:"McClelland's need theory — high nAch people prefer:",opts:["Easy tasks","Very hard tasks","Moderate difficulty with clear feedback","Tasks with no accountability"],ans:2,exp:"High nAch: prefer moderate difficulty, personal responsibility, clear performance feedback, calculated risks."},
  {q:"Cognitive Dissonance was proposed by:",opts:["Maslow","Festinger","Herzberg","Vroom"],ans:1,exp:"Leon Festinger (1957) proposed Cognitive Dissonance Theory — mental discomfort from conflicting beliefs."},
  {q:"'Halo Effect' in performance appraisal means:",opts:["All traits rated high due to one outstanding trait","Only recent events influence rating","Comparing to others","Giving average ratings"],ans:0,exp:"Halo Effect: one outstanding positive (or negative) trait unfairly influences ratings on ALL other traits."},
  {q:"Transformational leadership DIFFERS from Transactional in that it:",opts:["Focuses on reward exchanges","Inspires with vision and promotes change","Maintains strict discipline","Avoids empowering employees"],ans:1,exp:"Transformational: inspires with vision, promotes change, builds emotional bonds. Transactional: exchange-based."},
  {q:"Content theories of motivation explain:",opts:["HOW motivation occurs","WHAT motivates people (needs)","When motivation is highest","Who gets motivated"],ans:1,exp:"Content theories = WHAT motivates (needs): Maslow, Herzberg, McClelland, Alderfer. Process theories = HOW."},
  {q:"Maslow's HIGHEST need level is:",opts:["Esteem","Safety","Self-Actualization","Social"],ans:2,exp:"Self-Actualization = highest in Maslow's hierarchy. Realizing full potential, peak experiences, creativity."},
  {q:"Organizational Culture is BEST defined as:",opts:["Formal rules and policies","Shared values, beliefs and assumptions guiding behavior","Physical work environment","Organization chart"],ans:1,exp:"Organizational culture = shared values, beliefs, norms, and assumptions that define 'how things are done here'."},
  {q:"Fiedler's Contingency Model — effectiveness depends on fit between style and:",opts:["Team size","Situational favorableness","Budget","Industry type"],ans:1,exp:"Fiedler: effectiveness = fit between leadership style and situational favorableness (3 factors: leader-member relations, task structure, position power)."},
  {q:"Emotional Intelligence was popularized by:",opts:["Maslow","Goleman","McClelland","Fiedler"],ans:1,exp:"Daniel Goleman popularized EI in his 1995 book. 5 components: self-awareness, self-regulation, motivation, empathy, social skills."},
  {q:"If Expectancy = 0 in Vroom's theory, motivation = ?",opts:["High","Moderate","Zero","Depends on Valence"],ans:2,exp:"M = E×I×V. If ANY component = 0, motivation = 0. Expectancy=0 means person doesn't believe effort leads to performance."},
  {q:"Which theory distinguishes between two sets: job content and job context factors?",opts:["Maslow's Hierarchy","McGregor's XY Theory","Herzberg's Two-Factor Theory","Vroom's Expectancy"],ans:2,exp:"Herzberg distinguishes: Motivators (job content: achievement, recognition, the work itself) vs Hygiene (job context: salary, conditions)."},
  {q:"Laissez-faire leadership is MOST effective when:",opts:["Team needs direction","Team members are highly skilled and self-motivated","Crisis situation exists","New employees join"],ans:1,exp:"Laissez-faire works best with experienced, highly skilled, and self-motivated team members who don't need supervision."},
  {q:"Perception in OB refers to:",opts:["Physical vision","Process of interpreting sensory information to give it meaning","Memory recall","Learning process"],ans:1,exp:"Perception = the process by which individuals interpret and make sense of their sensory experiences."}
],

"hrm-hrm": [
  {q:"Kirkpatrick's Level 4 'Results' measures:",opts:["Trainee reactions","Learning gains","Behavior change","Organizational outcomes"],ans:3,exp:"Kirkpatrick Level 4 = ultimate organizational impact: productivity, quality, costs, sales, ROI."},
  {q:"MBO was popularized by:",opts:["Frederick Taylor","Peter Drucker","Henry Fayol","Elton Mayo"],ans:1,exp:"Peter Drucker introduced MBO in 'The Practice of Management' (1954)."},
  {q:"360° feedback involves input from:",opts:["Only superiors","Only peers","Superiors, peers, subordinates, customers & self","Only HR department"],ans:2,exp:"360° = multi-source: boss + peers + subordinates + customers + self-assessment."},
  {q:"Which recruitment source gives fresh perspectives?",opts:["Internal promotion","Employee referral","External sources (job portals, campus)","Internal transfer"],ans:2,exp:"External recruitment brings fresh perspectives, new ideas, and diverse talent. Internal is faster and cheaper."},
  {q:"Most SCIENTIFIC job evaluation method?",opts:["Job Ranking","Classification","Factor Comparison","Point Rating"],ans:3,exp:"Point Rating = most systematic and scientific: assigns points to compensable factors like skill, effort, responsibility."},
  {q:"'Vestibule training' takes place in:",opts:["On-the-job location","Replica of workplace away from actual production","Online only","Classroom only"],ans:1,exp:"Vestibule training = specially set up area replicating actual work environment, without production pressure."},
  {q:"Delphi Technique in HR is used for:",opts:["Training programs","Consensus forecasting using expert opinions","Performance appraisal","Job analysis"],ans:1,exp:"Delphi = iterative anonymous expert questionnaire method for reaching consensus in HR demand forecasting."},
  {q:"Job Analysis produces TWO main outputs:",opts:["Job evaluation + job enrichment","Job description + job specification","Training needs + career plan","Selection test + interview guide"],ans:1,exp:"Job Analysis → Job Description (duties/responsibilities) + Job Specification (required qualifications/skills)."},
  {q:"'Cafeteria benefits plan' means:",opts:["Company canteen","Employees choose from menu of benefits","Same benefits for all","Factory workers only"],ans:1,exp:"Cafeteria/flexible benefits plan: employees choose their own benefits package from a set of available options."},
  {q:"HR Planning first step is:",opts:["Recruiting candidates","Analyzing organizational objectives","Writing job descriptions","Conducting interviews"],ans:1,exp:"HR Planning begins with analyzing organizational objectives/strategy to determine what human resources are needed."},
  {q:"'Induction' in HRM refers to:",opts:["New employee orientation program","Promotion to senior level","Internal transfer","Performance review"],ans:0,exp:"Induction = orientation/onboarding program for new employees — familiarizes them with organization, culture, policies."},
  {q:"BARS stands for:",opts:["Balanced Assessment Rating System","Behaviorally Anchored Rating Scale","Basic Appraisal Rating Scale","Business Assessment Review System"],ans:1,exp:"BARS = Behaviorally Anchored Rating Scale. Uses specific behavioral examples as scale anchors for more objective appraisal."},
  {q:"Succession Planning is primarily about:",opts:["Recruiting fresh graduates","Identifying internal candidates for future key roles","Managing employee benefits","Handling grievances"],ans:1,exp:"Succession planning = identifying and developing internal talent to fill key positions when they become vacant."},
  {q:"Internal equity in compensation means:",opts:["Paying same as competitors","Fair pay relationship between jobs WITHIN the organization","Equal pay for men and women","Fixed pay regardless of performance"],ans:1,exp:"Internal equity = fair pay hierarchy within the organization, based on job evaluation (comparing jobs to each other)."},
  {q:"'Stress Interview' is designed to:",opts:["Relax the candidate","Test candidate's behavior and response under pressure","Evaluate technical skills","Check cultural fit"],ans:1,exp:"Stress interview = deliberately creates uncomfortable situations to observe how candidates handle pressure and stress."},
  {q:"HRIS stands for:",opts:["Human Resource Integration System","Human Resource Information System","HR Incentive System","Human Relations Input System"],ans:1,exp:"HRIS = Human Resource Information System. Software for managing HR data: payroll, attendance, performance, recruitment."},
  {q:"'Central Tendency' in performance appraisal means:",opts:["Giving extreme high ratings","Giving extreme low ratings","Giving average ratings to all to avoid conflict","Rating based on recent events only"],ans:2,exp:"Central tendency error: rater avoids extremes and rates everyone around the midpoint to avoid controversy."},
  {q:"KIRKPATRICK Level 1 (Reaction) is measured by:",opts:["Pre/post test","Supervisor observation","Smile sheet / feedback form","ROI calculation"],ans:2,exp:"Level 1 Reaction = immediate trainee feedback (smile sheet/evaluation form filled right after training)."},
  {q:"Training is different from Development in that Training is:",opts:["Long-term and future-focused","Short-term and current job-focused","For senior managers only","Conducted only off-the-job"],ans:1,exp:"Training = job-specific, short-term, current role. Development = broader, long-term, future roles and overall growth."},
  {q:"'Recency Bias' in appraisal means:",opts:["Rating based on first impression","Only recent performance events influence the rating","Rating based on one exceptional trait","Comparing to the best performer"],ans:1,exp:"Recency bias = appraisal influenced only by most recent events, ignoring performance throughout the entire review period."}
],

"hrm-labour": [
  {q:"Canteen mandatory in factory with workers ≥:",opts:["100","200","500","1000"],ans:2,exp:"Factories Act 1948: Canteen compulsory in factories employing 500 or more workers."},
  {q:"Minimum members to register a trade union?",opts:["5","7","10","15"],ans:1,exp:"Trade Unions Act 1926: Minimum 7 members required to apply for registration of a trade union."},
  {q:"Industrial Disputes Act, 1947 — 'retrenchment' means:",opts:["Temporary layoff","Termination for surplus, not as punishment","Lock-out by employer","Voluntary retirement"],ans:1,exp:"Retrenchment = termination of surplus workers. NOT punishment, not superannuation, not VRS."},
  {q:"Payment of Wages Act 1936 deadline for establishments with >1000 workers:",opts:["5 days","7 days","10 days","15 days"],ans:2,exp:">1000 workers: wages must be paid within 10 days of wage period end. ≤1000: within 7 days."},
  {q:"Crèche facility required in factory with ___ women workers:",opts:["10","20","30","50"],ans:2,exp:"Factories Act 1948: Crèche mandatory for factories employing 30 or more women workers."},
  {q:"Minimum Wages Act 1948 — wages must be revised every:",opts:["1 year","3 years","5 years","10 years"],ans:2,exp:"Minimum Wages Act 1948: minimum wages must be reviewed and revised at least every 5 years."},
  {q:"Standing Orders Act 1946 applies to establishments with:",opts:["10+","50+","100+","500+"],ans:2,exp:"Industrial Employment (Standing Orders) Act 1946 applies to establishments employing 100 or more workmen."},
  {q:"'Lock-out' is defined as:",opts:["Workers refusing to work","Employer's temporary closing of workplace","Permanent factory closure","Management strike"],ans:1,exp:"Lock-out = employer's temporary closing of place of business, or refusal to employ workers."},
  {q:"Payment of Bonus Act 1965 applies to establishments with:",opts:["10+","20+","50+","100+"],ans:1,exp:"Payment of Bonus Act 1965 applies to factories and establishments employing 20 or more persons."},
  {q:"Workmen's Compensation Act 1923 covers:",opts:["Voluntary resignation","Employment-related accidents and occupational diseases","Retrenchment","Maternity"],ans:1,exp:"WC Act 1923: compensation to workers for accidents and occupational diseases arising out of employment."},
  {q:"Equal Remuneration Act 1976 ensures:",opts:["Minimum wages","Equal pay for equal work regardless of gender","Bonus payments","Overtime compensation"],ans:1,exp:"Equal Remuneration Act 1976 = equal pay to men and women for the same or similar work."},
  {q:"'Collective Bargaining' is a process of:",opts:["Government setting wages","Workers' and employers' representatives negotiating","Courts determining wages","HR department setting policies"],ans:1,exp:"Collective bargaining = negotiation between employer and workers' representatives (union) on wages, conditions, employment terms."},
  {q:"ESI Act 1948 provides which benefit?",opts:["Housing loan","Sickness benefit","Education loan","Pension only"],ans:1,exp:"ESI provides: medical, sickness, maternity, disablement, dependent benefits. Housing loan is NOT an ESI benefit."},
  {q:"Trade Unions Act was enacted in:",opts:["1919","1922","1926","1930"],ans:2,exp:"Trade Unions Act = 1926. First legislation giving legal recognition and protection to trade unions in India."},
  {q:"Industrial Disputes Act — which authority handles disputes of national importance?",opts:["Labour Court","Industrial Tribunal","National Tribunal","Conciliation Officer"],ans:2,exp:"National Tribunal = adjudicates disputes of national importance or those in multiple states."},
  {q:"SARFAESI Act 2002 helps banks to:",opts:["Give fresh loans easily","Recover NPA by taking possession of collateral without court","Issue bonds","Increase deposits"],ans:1,exp:"SARFAESI enables banks to enforce security interest and sell secured assets to recover NPAs without court intervention."},
  {q:"Code on Social Security 2020 consolidates how many labour laws?",opts:["5","7","9","11"],ans:2,exp:"Code on Social Security 2020 amalgamates 9 central labour laws related to social security."},
  {q:"Maximum working hours per week under Factories Act 1948?",opts:["40 hours","44 hours","48 hours","52 hours"],ans:2,exp:"Factories Act 1948: Maximum 48 hours per week (9 hours per day) for adult workers."},
  {q:"'Gherao' in industrial relations means:",opts:["Strike","Physical encirclement of management/employer","Lock-out","Picketing"],ans:1,exp:"Gherao = workers physically surround/encircle managers or employers, preventing them from leaving."},
  {q:"Under ID Act 1947, a 'layoff' entitles worker to:",opts:["Full wages","50% of basic wages + DA","No compensation","VRS benefits"],ans:1,exp:"Layoff compensation = 50% of total basic wages and dearness allowance for the period of layoff."}
],

"mgmt-strategic": [
  {q:"BCG Matrix — high market share in slow-growing market is called:",opts:["Star","Question Mark","Cash Cow","Dog"],ans:2,exp:"Cash Cow = high relative market share + low market growth. Generates more cash than needed."},
  {q:"Balanced Scorecard developed by:",opts:["Porter and Ansoff","Kaplan and Norton","Mintzberg and Quinn","Miles and Snow"],ans:1,exp:"Robert S. Kaplan and David P. Norton developed Balanced Scorecard, published in HBR 1992."},
  {q:"SWOT — Strengths and Weaknesses are:",opts:["External factors","Internal factors","Industry factors","Market factors"],ans:1,exp:"S & W = INTERNAL (within the company). O & T = EXTERNAL (environmental factors)."},
  {q:"Porter's Five Forces does NOT include:",opts:["Threat of new entrants","Supplier power","Government regulatory power","Competitive rivalry"],ans:2,exp:"Porter's Five Forces: Rivalry, New Entrants, Substitutes, Buyers, Suppliers. Government is NOT one of the 5."},
  {q:"'Stars' in BCG Matrix require:",opts:["Cash withdrawal/harvesting","Heavy investment to maintain","Immediate divestment","No special strategy"],ans:1,exp:"Stars = high growth + high market share. Need heavy investment to maintain growth and position."},
  {q:"PESTLE — 'E' in last position stands for:",opts:["Economic","Entrepreneurial","Environmental","External"],ans:2,exp:"PESTLE = Political, Economic, Social, Technological, Legal, Environmental."},
  {q:"Porter's Generic Strategies — 'Stuck in the middle' means:",opts:["Average-sized company","No clear competitive strategy — performs poorly","Targeting middle market","Medium pricing"],ans:1,exp:"Stuck in the middle = lacks clear Cost Leadership OR Differentiation strategy → below-average performance."},
  {q:"BCG Matrix was developed by:",opts:["Michael Porter","Bruce Henderson (BCG)","Ansoff","Kaplan"],ans:1,exp:"Bruce Henderson developed the BCG Growth-Share Matrix in 1970 at Boston Consulting Group."},
  {q:"SWOT analysis is attributed to:",opts:["Michael Porter","Kenneth Andrews","Igor Ansoff","Kaplan & Norton"],ans:1,exp:"SWOT framework is attributed to Kenneth Andrews and colleagues at Harvard Business School (1960s-70s)."},
  {q:"Ansoff Matrix 'Market Development' strategy means:",opts:["New product in existing market","Existing product in new market","New product in new market","Existing product in existing market"],ans:1,exp:"Market Development = selling existing products to new markets (new geographic areas or new customer segments)."},
  {q:"Balanced Scorecard Learning & Growth perspective includes:",opts:["Revenue metrics","Customer satisfaction scores","Employee skills and culture","Process efficiency"],ans:2,exp:"Learning & Growth = human capital (employee skills), information capital (IT systems), organizational culture."},
  {q:"Porter's differentiation strategy focuses on:",opts:["Being lowest-cost producer","Offering unique product/service that commands premium","Targeting narrow market segments","Reducing production costs"],ans:1,exp:"Differentiation = offering unique, distinctive products/services that allow charging premium prices (e.g., Apple, BMW)."},
  {q:"In BCG Matrix, 'Dogs' strategy is typically:",opts:["Invest heavily","Harvest remaining profits or divest","Build market share","Maintain status quo"],ans:1,exp:"Dogs = low growth + low share. Strategy: harvest remaining profits, then divest/exit the market."},
  {q:"Porter's Five Forces — many suppliers means:",opts:["High supplier power (unfavorable)","Low supplier power (favorable)","No impact on profitability","Depends on industry"],ans:1,exp:"Many suppliers = low bargaining power of suppliers = favorable for the buying firm (can switch easily)."},
  {q:"Corporate Social Responsibility (CSR) in India under Companies Act 2013 is mandatory for companies with net profit ≥:",opts:["₹1 crore","₹5 crore","₹10 crore","₹50 crore"],ans:1,exp:"CSR mandatory for: net worth ₹500cr+ OR turnover ₹1000cr+ OR net profit ₹5 crore+."},
  {q:"SWOT 'O' (Opportunities) refers to:",opts:["Company's strengths","Internal capabilities","Favorable external trends","Company weaknesses"],ans:2,exp:"Opportunities = favorable external factors in the environment that the company can exploit."},
  {q:"Fiedler's Contingency Model measures leader's orientation using:",opts:["Leadership style questionnaire","LPC (Least Preferred Co-worker) scale","360° feedback","MBTI assessment"],ans:1,exp:"Fiedler uses LPC (Least Preferred Co-worker) scale to determine if a leader is task-oriented or relationship-oriented."},
  {q:"Ansoff Matrix 'Diversification' means:",opts:["Existing product, existing market","New product, new market","Existing product, new market","New product, existing market"],ans:1,exp:"Diversification (highest risk) = new products + new markets. Company enters completely unfamiliar territory."},
  {q:"Blue Ocean Strategy was proposed by:",opts:["Michael Porter","Kim and Mauborgne","Kaplan and Norton","Mintzberg"],ans:1,exp:"Blue Ocean Strategy (2005) by W. Chan Kim and Renée Mauborgne. Create uncontested market space instead of competing."},
  {q:"'Question Marks' in BCG Matrix are also called:",opts:["Cash generators","Problem children/Wild cats","Rising stars","Established players"],ans:1,exp:"Question Marks = also called Problem Children or Wild Cats. High growth but low market share — uncertain future."}
],

"mgmt-ba": [
  {q:"Which analytics answers 'What will happen in future?'",opts:["Descriptive","Diagnostic","Predictive","Prescriptive"],ans:2,exp:"Predictive Analytics = uses historical data, statistical models, ML to forecast future outcomes."},
  {q:"R² in regression represents:",opts:["Correlation coefficient","Proportion of variance in Y explained by X","Statistical significance","Standard error"],ans:1,exp:"R² (coefficient of determination) = proportion of Y's variance explained by X. Range: 0 to 1."},
  {q:"5 Vs of Big Data — which refers to data accuracy?",opts:["Volume","Velocity","Variety","Veracity"],ans:3,exp:"Veracity = accuracy, reliability, and quality of data. Big data can contain noise and inconsistencies."},
  {q:"p-value < 0.05 means:",opts:["Null hypothesis accepted","Statistically significant — reject null hypothesis","Sample too small","Data is normal"],ans:1,exp:"p < 0.05 (at α=0.05 level): reject H₀. Result is statistically significant."},
  {q:"Normal distribution is also called:",opts:["Poisson distribution","Bell curve","Binomial","Skewed distribution"],ans:1,exp:"Normal distribution = bell-shaped curve. Symmetric. Mean=Median=Mode. 68-95-99.7 rule."},
  {q:"ANOVA compares:",opts:["Two proportions","Means of two groups","Means of three or more groups","Two standard deviations"],ans:2,exp:"ANOVA = Analysis of Variance. Tests whether means of 3+ groups are significantly different."},
  {q:"Prescriptive analytics goes beyond prediction to:",opts:["Describe past","Diagnose why","Recommend optimal actions","Store data"],ans:2,exp:"Prescriptive analytics = recommends specific actions/decisions to optimize outcomes. Highest level."},
  {q:"Coefficient of Variation (CV) is used to:",opts:["Measure central tendency","Compare variability across different scales","Test hypotheses","Calculate regression"],ans:1,exp:"CV = (SD/Mean)×100. Used to compare relative variability between datasets with different units or means."},
  {q:"In Y = a + bX regression, 'b' represents:",opts:["Y-intercept","Slope: change in Y per 1-unit change in X","R-squared","Standard error"],ans:1,exp:"'b' = slope/regression coefficient. For each 1-unit increase in X, Y changes by 'b' units."},
  {q:"Business Intelligence (BI) tools primarily used for:",opts:["Writing code","Analyzing and visualizing data for decisions","HR records only","Manufacturing orders"],ans:1,exp:"BI tools (Tableau, Power BI) = analyze, visualize, present data to support better business decisions."},
  {q:"Original 3 Vs of Big Data (Gartner)?",opts:["Volume, Velocity, Veracity","Volume, Velocity, Variety","Variety, Veracity, Value","Volume, Variety, Value"],ans:1,exp:"Original 3 Vs by Gartner: Volume, Velocity, Variety. Veracity and Value added later by others."},
  {q:"'Diagnostic analytics' answers:",opts:["What happened?","Why did it happen?","What will happen?","What should we do?"],ans:1,exp:"Diagnostic analytics = why did it happen? Drill-down analysis, root cause analysis, correlation analysis."},
  {q:"Standard deviation is:",opts:["Average of deviations","Square root of variance","Sum of squared deviations","Mean absolute deviation"],ans:1,exp:"Standard deviation (σ) = √variance. Measures spread of data in same units as the data."},
  {q:"Chi-Square test is used for:",opts:["Comparing two means","Testing independence of categorical variables","Comparing three or more means","Regression analysis"],ans:1,exp:"Chi-Square test: tests whether two categorical variables are independent or associated."},
  {q:"Type I error in hypothesis testing means:",opts:["Accepting false null hypothesis","Rejecting true null hypothesis","Sample too small","Wrong data collected"],ans:1,exp:"Type I error (α error) = rejecting a true null hypothesis (false positive). Also called 'False Alarm'."},
  {q:"Machine Learning is MOST associated with which analytics type?",opts:["Descriptive","Diagnostic","Predictive","Historical"],ans:2,exp:"Predictive analytics heavily uses Machine Learning algorithms to build forecasting models."},
  {q:"Which measure of central tendency is NOT affected by outliers?",opts:["Mean","Mode","Median","Weighted Mean"],ans:2,exp:"Median = middle value of sorted data. Not affected by extreme values (outliers). Use for skewed distributions."},
  {q:"'Data warehouse' is used for:",opts:["Real-time transaction processing","Storing historical data for analysis and reporting","Email storage","Application development"],ans:1,exp:"Data warehouse = central repository of integrated historical data from multiple sources, used for analysis and BI."},
  {q:"'Sampling error' occurs when:",opts:["Measuring the wrong variable","Sample does not accurately represent the population","Data entry mistakes","Software bugs"],ans:1,exp:"Sampling error = discrepancy between sample statistics and population parameters due to random sampling variation."},
  {q:"Descriptive analytics uses which tools PRIMARILY?",opts:["Machine learning models","Dashboards, reports, summary statistics","Predictive algorithms","Simulation models"],ans:1,exp:"Descriptive analytics = dashboards, reports, charts, summary statistics to describe what has happened."}
],

// ===== SBI PO QUESTIONS =====
"sbi-di": [
  {q:"Pie chart expenses: Food=30%, Rent=25%, Transport=15%, Savings=20%, Other=10%. Income=₹50,000. Amount saved?",opts:["₹8,000","₹9,000","₹10,000","₹12,000"],ans:2,exp:"Savings = 20% of ₹50,000 = ₹10,000."},
  {q:"Sales (₹ crore): 2020=40, 2021=50, 2022=60, 2023=55, 2024=70. % increase from 2020 to 2024?",opts:["50%","65%","75%","80%"],ans:2,exp:"Increase = (70-40)/40 × 100 = 30/40 × 100 = 75%."},
  {q:"Company has 60 employees. 40% Sales, 35% HR, rest Finance. How many in Finance?",opts:["12","13","15","18"],ans:2,exp:"Sales=24, HR=21. Finance=60-45=15."},
  {q:"Bar chart: Monthly profits ₹L — Jan:5, Feb:7, Mar:9, Apr:6, May:8. Average profit per month?",opts:["₹6L","₹6.5L","₹7L","₹7.5L"],ans:2,exp:"Average = (5+7+9+6+8)/5 = 35/5 = ₹7L."},
  {q:"Line graph: Revenue grew from ₹100 crore (2022) to ₹130 crore (2024). CAGR (2 years) approx?",opts:["10%","13%","14%","15%"],ans:2,exp:"CAGR = (130/100)^(1/2) − 1 ≈ 1.14 − 1 = 14%."},
  {q:"Pie chart: Market share — A=40%, B=25%, C=20%, D=15%. Total market=₹200 crore. B's revenue?",opts:["₹40 crore","₹45 crore","₹50 crore","₹55 crore"],ans:2,exp:"B = 25% of 200 = ₹50 crore."},
  {q:"Caselet: 500 students. 60% pass. Of those who pass, 40% get distinction. Students with distinction?",opts:["100","110","120","130"],ans:2,exp:"Pass = 300. Distinction = 40% of 300 = 120."},
  {q:"Data sufficiency: Area of rectangle? St.I: Perimeter = 28. St.II: Length = twice breadth.",opts:["I alone","II alone","Either alone","Both needed"],ans:3,exp:"I: l+b=14. II: l=2b. Both: b=14/3, l=28/3. Need both to find area."},
  {q:"Table: Bank loans disbursed — 2022: ₹50L, 2023: ₹65L, 2024: ₹80L. % growth 2022 to 2024?",opts:["40%","50%","60%","65%"],ans:2,exp:"Growth = (80-50)/50 × 100 = 60%."},
  {q:"Mixed DI: Revenue=₹200 crore, expenses=₹160 crore. If revenue grows 10% and expense grows 5% next year, new profit?",opts:["₹48 crore","₹52 crore","₹56 crore","₹60 crore"],ans:1,exp:"New Revenue=220, New Expense=168. New Profit=220-168=₹52 crore."},
  {q:"Pie chart: 120° sector represents what percentage?",opts:["25%","30%","33.3%","40%"],ans:2,exp:"% = (120/360)×100 = 33.3%."},
  {q:"Line graph: Stock price Mon=100, Tue=110, Wed=105, Thu=115, Fri=120. Day with highest % increase?",opts:["Monday to Tuesday","Wednesday to Thursday","Thursday to Friday","Tuesday to Wednesday"],ans:0,exp:"Mon→Tue: (110-100)/100×100 = 10%. Others: 9.5%, 4.3%, -4.5%. Highest = Mon→Tue."},
  {q:"Caselet: A shop sells 3 items: A at ₹50 (20 units), B at ₹80 (15 units), C at ₹100 (10 units). Total revenue?",opts:["₹2,700","₹3,200","₹3,700","₹4,200"],ans:1,exp:"Revenue = 50×20 + 80×15 + 100×10 = 1000+1200+1000 = ₹3,200."},
  {q:"If ratio of income to expenditure is 5:4 and savings=₹6,000, what is income?",opts:["₹24,000","₹28,000","₹30,000","₹36,000"],ans:2,exp:"Income=5x, Exp=4x. Savings=x=6000. Income=5×6000=₹30,000."},
  {q:"Bar chart: Products A,B,C — Profit%: A=20%, B=15%, C=25%. If all have same CP=₹100, total SP of all three?",opts:["₹355","₹360","₹370","₹380"],ans:1,exp:"SP: A=120, B=115, C=125. Total=120+115+125=₹360."},
  {q:"Tabular DI: 4 students, marks out of 500: 350, 420, 380, 450. What % scored above 400?",opts:["25%","50%","60%","75%"],ans:1,exp:"Above 400: 420 and 450 = 2 students. 2/4 × 100 = 50%."},
  {q:"Revenue grows 20% YoY; Expenses grow 10% YoY. Original profit margin = 25%. New profit margin?",opts:["Below 25%","Equal to 25%","Above 25%","Cannot determine"],ans:2,exp:"Rev=100→120, Exp=75→82.5. Old profit=25. New profit=37.5. Margin=37.5/120×100=31.25% > 25%."},
  {q:"Caselet: Company A has 3 departments. HR=30 employees (avg salary ₹40K), Finance=20 (₹60K), IT=50 (₹80K). Total monthly wage bill?",opts:["₹58L","₹62L","₹64L","₹70L"],ans:2,exp:"HR=30×40=₹12L, Finance=20×60=₹12L, IT=50×80=₹40L. Total=₹64L."},
  {q:"Pie chart: A company's cost split — Materials=45%, Labour=30%, Overhead=15%, Profit=10%. If profit=₹5L, total revenue?",opts:["₹40L","₹45L","₹50L","₹55L"],ans:2,exp:"10% of Revenue = ₹5L → Revenue = ₹50L."},
  {q:"Data Sufficiency: Is X a prime number? St.I: X is odd. St.II: X is between 10 and 20.",opts:["I alone","II alone","Both needed","Neither sufficient"],ans:3,exp:"I alone: odd numbers include 9, 15 (not prime). II alone: includes 11,13 (prime), 15 (not prime). Both: 11, 13 (prime), 15 (not prime). Neither sufficient."}
],

"sbi-english": [
  {q:"Essay intro best practice — which sentence is BEST to start a formal essay?",opts:["I think digital India is good","In the era of rapid digitalization, India stands at a pivotal crossroads between opportunity and challenge","Digital India is a very good scheme","Let me tell you about digital India"],ans:1,exp:"Formal essay: no 'I think', no informal language. Start with context + topic + what you'll discuss."},
  {q:"Formal letter closing when recipient is UNKNOWN (Dear Sir/Madam):",opts:["Yours lovingly","Yours affectionately","Yours faithfully","Thanks and regards"],ans:2,exp:"Yours faithfully = unknown recipient (Dear Sir/Madam). Yours sincerely = when you know their name."},
  {q:"Precis of a 300-word passage should be approximately:",opts:["50 words","75 words","100 words","150 words"],ans:2,exp:"Precis = 1/3 of original. 300 ÷ 3 = 100 words."},
  {q:"The word AMELIORATE in formal writing means:",opts:["Worsen","Maintain","Improve","Evaluate"],ans:2,exp:"Ameliorate = to improve a bad situation. Frequently used in formal banking/policy writing."},
  {q:"Error: 'The committee have taken a unanimous decision to postpone the event.'",opts:["The committee have","taken a unanimous","decision to postpone","the event"],ans:0,exp:"'Committee' = singular collective noun → 'has taken' (not 'have taken')."},
  {q:"Which word replaces VERBOSE appropriately? 'Her essay was verbose and difficult to follow.'",opts:["Concise","Wordy","Clear","Short"],ans:1,exp:"Verbose = using too many words. The sentence describes a quality — 'wordy' is the synonym. (The question asks for synonym here.)"},
  {q:"Fill: The RBI ____ the repo rate to curb inflationary pressure in the economy.",opts:["deposited","hiked","ignored","printed"],ans:1,exp:"'Hiked' = increased. RBI hikes repo rate to make borrowing costlier, reducing money supply, curbing inflation."},
  {q:"Para jumble FIRST sentence CANNOT start with:",opts:["'Banks play...'","'The banking sector...'","'However, challenges remain...'","'In recent years...'"],ans:2,exp:"'However' is a contrast connector — it always refers to a previous sentence. So it CANNOT be the first sentence (nothing comes before to contrast with)."},
  {q:"RC Inference: Passage says 'Despite rapid growth, financial literacy remains alarmingly low in rural areas.' Author's tone?",opts:["Celebratory","Critically concerned","Neutral","Humorous"],ans:1,exp:"'Despite' (dismisses positive) + 'alarmingly low' (strong negative qualifier) = author is critically concerned about the state."},
  {q:"Sentence Correction: 'Revert back to our email at the earliest.' Error?",opts:["No error","'Revert back' is redundant — use 'revert'","'at the earliest' is wrong","'our email' is wrong"],ans:1,exp:"'Revert' already means 'to go back/reply'. 'Revert back' is redundant. Correct: 'Please revert to our email.'"},
  {q:"Cloze: 'Banks serve as the _____ of the economy, facilitating growth through credit creation.'",opts:["burden","backbone","barrier","benefactor"],ans:1,exp:"'Backbone' = the chief support structure. Banks are the backbone of the economy — supports it from within."},
  {q:"Formal vs informal — which is FORMAL?",opts:["'You guys need to pay up soon.'","'We request you to clear the outstanding dues at the earliest convenience.'","'Hey, your payment is late!'","'Sort your dues ASAP please!'"],ans:1,exp:"'We request you to...' uses polite, formal language. All others are informal or rude."},
  {q:"Vocabulary: FRUGAL means:",opts:["Generous","Economical and careful with money","Extravagant","Careless"],ans:1,exp:"Frugal = careful and economical in use of resources. Antonym = extravagant/lavish."},
  {q:"Grammar: 'Neither the manager nor the employees _____ present at the meeting.'",opts:["was","were","is","are"],ans:1,exp:"Neither...nor: verb agrees with NEARER subject. 'Employees' (plural) is nearer → 'were'."},
  {q:"'Had I known about the fraud earlier, I _____ reported it immediately.'",opts:["would","would have","will have","shall"],ans:1,exp:"Third conditional (past unreal/regret): 'Had I known... I would have reported.' Correct form = would have + past participle."},
  {q:"Which is the correct use of 'affect' vs 'effect'?",opts:["The effect of rain affects crops","The affect of rain effects crops","The effect of rain effected crops","The affect of rain affected crops"],ans:0,exp:"'Effect' (noun) = result. 'Affect' (verb) = to influence. 'The EFFECT (noun) of rain AFFECTS (verb) crops.' Correct usage."},
  {q:"Precis writing rule: which should be REMOVED from original?",opts:["Main arguments","Key statistics","Examples and repetitions","Topic sentences"],ans:2,exp:"Precis removes: examples, illustrations, repetitions, elaborations. It RETAINS: main ideas, key statistics, arguments, topic sentences."},
  {q:"Essay topic: 'AI in Banking'. Which counter-argument is MOST balanced?",opts:["AI is completely bad for banking","AI has no role in banking","While AI improves efficiency, concerns about job displacement and cybersecurity must be addressed","AI should be banned from banking"],ans:2,exp:"A counter-argument acknowledges both sides. 'While AI improves efficiency, concerns about...' shows balanced, nuanced thinking — which evaluators reward."},
  {q:"Vocabulary in Context: 'The bank's liquidity position was robust despite market turbulence.' ROBUST means?",opts:["Weak","Strong and healthy","Uncertain","Declining"],ans:1,exp:"Robust = strong, sturdy, in good condition. In financial context = healthy, able to withstand pressure."},
  {q:"Error: 'The number of students in the exam are increasing every year.'",opts:["The number of","students in","the exam","are increasing"],ans:3,exp:"'The number of' takes a SINGULAR verb. Correct: 'The number of students... IS increasing.' (Compare: 'A number of students ARE increasing' — different!)"}
],

"sbi-banking": [
  {q:"SBI was formed in 1955 from which bank?",opts:["Reserve Bank of India","Bank of India","Imperial Bank of India","Central Bank of India"],ans:2,exp:"State Bank of India was formed in 1955 by nationalizing the Imperial Bank of India (est. 1921)."},
  {q:"Monetary Policy Committee (MPC) has how many members?",opts:["3","4","5","6"],ans:3,exp:"MPC = 6 members: 3 from RBI (Governor chairs, + 2 RBI officials) + 3 external members appointed by Government."},
  {q:"Which committee recommended Small Finance Banks?",opts:["Narasimham Committee","Nachiket Mor Committee","Raghuram Rajan Committee","Urjit Patel Committee"],ans:1,exp:"Nachiket Mor Committee (2013) recommended differentiated banking licences including Small Finance Banks."},
  {q:"RBI's inflation target under flexible inflation targeting?",opts:["2% ± 1%","4% ± 2%","6% ± 2%","3% ± 1%"],ans:1,exp:"RBI targets CPI inflation at 4% with tolerance band of ±2% (range: 2%-6%)."},
  {q:"OMO (Open Market Operations) means:",opts:["RBI selling goods publicly","RBI buying/selling government securities to manage liquidity","Banks opening branches freely","Foreign currency exchange"],ans:1,exp:"OMO = RBI buys/sells government securities in open market to inject or absorb liquidity from banking system."},
  {q:"SBI's associate banks were merged into SBI in which year?",opts:["2014","2015","2017","2019"],ans:2,exp:"5 associate banks + Bharatiya Mahila Bank merged into SBI in 2017, making SBI significantly larger."},
  {q:"Priority Sector Lending (PSL) target for domestic commercial banks is:",opts:["30% of ANBC","40% of ANBC","50% of ANBC","20% of ANBC"],ans:1,exp:"Domestic commercial banks must lend 40% of Adjusted Net Bank Credit (ANBC) to priority sectors (agriculture, MSME, education, housing)."},
  {q:"SARFAESI Act 2002 allows banks to:",opts:["Give unsecured loans freely","Recover NPA by taking possession of collateral without court","Merge with other banks","Issue new shares"],ans:1,exp:"SARFAESI enables banks to enforce security interest and sell secured assets to recover bad loans without court intervention."},
  {q:"Which is a Payment Bank in India?",opts:["Jana Bank","AU Small Finance Bank","Airtel Payments Bank","IDFC First Bank"],ans:2,exp:"Airtel Payments Bank is a Payment Bank (limited services, no loans). Jana and AU are Small Finance Banks. IDFC First = private sector bank."},
  {q:"SLR (Statutory Liquidity Ratio) assets must include:",opts:["Cash only","Gold only","Cash, gold, and approved government securities","Foreign currency"],ans:2,exp:"SLR = banks must maintain % of deposits in: cash + gold + approved government and approved securities."},
  {q:"CPI stands for — and is used by RBI for:",opts:["Consumer Price Index — monetary policy","Consumer Product Index — trade policy","Cost Price Index — banking policy","Credit Price Index — lending"],ans:0,exp:"CPI = Consumer Price Index. RBI uses CPI (not WPI) as the headline inflation measure for monetary policy decisions."},
  {q:"'Lender of Last Resort' is a function of:",opts:["SBI","Ministry of Finance","RBI","SEBI"],ans:2,exp:"RBI acts as Lender of Last Resort — provides emergency liquidity to banks in crisis that cannot borrow from elsewhere."},
  {q:"SWIFT code is used for:",opts:["Domestic NEFT transfers","International bank identification in cross-border transactions","ATM cash withdrawals","UPI payments"],ans:1,exp:"SWIFT (Society for Worldwide Interbank Financial Telecommunication) code uniquely identifies banks in international financial transactions."},
  {q:"Base Rate was replaced by MCLR in which year?",opts:["2014","2015","2016","2017"],ans:2,exp:"MCLR (Marginal Cost of funds-based Lending Rate) replaced the Base Rate system in April 2016."},
  {q:"Fiscal Deficit means:",opts:["Trade deficit","Government expenditure exceeds revenue (funded by borrowing)","Current account deficit","Bank NPA excess"],ans:1,exp:"Fiscal Deficit = total government expenditure minus total revenue (excluding borrowings). Bridged by borrowing from market."},
  {q:"GVA (Gross Value Added) formula?",opts:["GDP + Taxes - Subsidies","GDP - Taxes + Subsidies","GDP × Inflation rate","GDP / Population"],ans:1,exp:"GVA = GDP - Net Taxes on Products (= GDP - Taxes + Subsidies). GVA measures value added by all producers."},
  {q:"Which regulates commodity markets in India (after 2015)?",opts:["RBI","SEBI","FMC","IRDAI"],ans:1,exp:"After merger of FMC (Forward Markets Commission) into SEBI in September 2015, SEBI regulates both capital markets AND commodity markets."},
  {q:"Standing Deposit Facility (SDF) differs from Reverse Repo in that:",opts:["SDF has higher rate","SDF requires no collateral from banks","SDF is for longer duration","SDF is used for foreign exchange"],ans:1,exp:"SDF (introduced April 2022) allows banks to park excess funds with RBI WITHOUT providing collateral, unlike Reverse Repo which requires government securities."},
  {q:"NABARD's primary focus is:",opts:["Urban infrastructure","Agricultural and rural development finance","Foreign trade","Capital markets"],ans:1,exp:"NABARD = National Bank for Agriculture and Rural Development. Provides refinance and development credit for agriculture and rural sectors."},
  {q:"India's current account deficit (CAD) occurs when:",opts:["Government spends more than revenue","Imports of goods and services exceed exports","Banks have more NPAs","RBI prints excess money"],ans:1,exp:"Current Account Deficit = imports of goods, services, and transfers exceed exports. Means India pays more to world than it earns from world."}
],

"sbi-reasoning": [
  {q:"Statement: 'Banks should give loans only to salaried individuals.' Which WEAKENS this?",opts:["Salaried people always repay loans","Self-employed often have better repayment records than salaried","Banks profit from all loan types","The government supports this policy"],ans:1,exp:"The premise assumes salaried = safer. If self-employed have better records, the premise is undermined — directly weakens the argument."},
  {q:"Statement: 'All companies should go digital.' Assumption?",opts:["Some companies are already digital","Companies currently use non-digital methods (otherwise advice is pointless)","Digital is expensive","The government mandates digital"],ans:1,exp:"If companies already were fully digital, the statement would be meaningless. Assumption: they currently use non-digital methods."},
  {q:"Critical Reasoning: 'Remote work increases productivity.' Which STRENGTHENS this?",opts:["Some remote workers are unproductive","Remote workers save commute time for work","Managers prefer office environment","Remote work has security risks"],ans:1,exp:"Saving commute time = more time available for productive work. This directly supports the claim that remote work increases productivity."},
  {q:"Double-row arrangement: Row 1 faces South. Row 2 faces North. A is in Row 1 position 3. Who does A face?",opts:["Row 2 position 1","Row 2 position 3","Row 2 position 5","Row 1 position 3"],ans:1,exp:"In facing-row arrangements, person at position 3 in Row 1 directly faces person at position 3 in Row 2 (mirror positions)."},
  {q:"Input-Output: 'rice bread tea milk' → Step I: 'milk rice bread tea'. Logic?",opts:["Alphabetical","Last word moves to first","Reverse order","First word moves to last"],ans:1,exp:"'milk' (last word) moved to first position. Rest shifted right. Logic: last word moves to first each step."},
  {q:"Syllogism: All managers are leaders. Some leaders are introverts. Conclusion: Some managers are introverts — does it follow?",opts:["Yes, follows","No, does not follow","Data insufficient","Only if all leaders are introverts"],ans:1,exp:"Some leaders are introverts, but those introverts may NOT be the managers. All managers are leaders, but only SOME leaders are introverts. Cannot conclude."},
  {q:"Statement-Course of Action: 'Cyberfraud in banking is rising.' Appropriate action?",opts:["Close all online banking","Invest in advanced cybersecurity systems and educate customers","Ignore the trend","Reduce banking staff"],ans:1,exp:"A practical, targeted action that directly addresses the problem. Option A is extreme. Option C is irresponsible. Option D is irrelevant."},
  {q:"Series: 2, 5, 11, 23, 47, ___",opts:["94","95","96","97"],ans:1,exp:"Pattern ×2+1: 2×2+1=5, 5×2+1=11, 11×2+1=23, 23×2+1=47, 47×2+1=95."},
  {q:"Cause and Effect: (I) Interest rates rose sharply. (II) Home loan demand fell significantly.",opts:["I is cause, II is effect","II is cause, I is effect","Both are independent events","Both are effects of same cause"],ans:0,exp:"Rising interest rates directly cause reduced loan demand (loans become more expensive). I→II is the logical causal direction."},
  {q:"Logic gate: AND gate with inputs A=1, B=1, C=0. Output?",opts:["0","1","Depends","2"],ans:0,exp:"AND gate: output is 1 ONLY when ALL inputs are 1. Since C=0, output = 0."},
  {q:"Data sufficiency: Is N divisible by 6? St.I: N divisible by 2. St.II: N divisible by 3.",opts:["I alone sufficient","II alone sufficient","Either alone sufficient","Both together needed"],ans:3,exp:"6=2×3. Need N divisible by BOTH 2 AND 3. Neither statement alone is sufficient. Both together → sufficient."},
  {q:"Critical Reasoning scope test: Passage about 'urban banking penetration'. Which answer is OUT OF SCOPE?",opts:["Urban banking accessibility has improved","ATMs in cities have increased","Rural banking needs similar improvement","Urban bank profits increased"],ans:2,exp:"The passage is about urban banking. 'Rural banking' is OUTSIDE the scope of the argument. Correct answers must stay within the stated topic."},
  {q:"Arrangement: A, B, C, D, E sit in a row. A is to the left of B. D is to the right of E. C is in the middle. If E is leftmost, order is?",opts:["E D C A B","E C D A B","E A C D B","E A B C D"],ans:0,exp:"E is leftmost. C is middle (position 3). A is left of B. D is right of E. Possible: E(1), D(2), C(3), A(4), B(5). Checking: A(4) left of B(5)✓, D(2) right of E(1)✓."},
  {q:"Computer: OSI model has how many layers?",opts:["5","6","7","8"],ans:2,exp:"OSI model has 7 layers: Physical, Data Link, Network, Transport, Session, Presentation, Application."},
  {q:"What does SQL stand for?",opts:["Structured Query Language","Standard Query Listing","Structured Question Layout","Simple Query Logic"],ans:0,exp:"SQL = Structured Query Language. Used to manage and query relational databases (SELECT, INSERT, UPDATE, DELETE)."},
  {q:"Assertion (A): India needs stronger financial literacy programs. Reason (R): Most rural citizens don't use formal banking. Relation?",opts:["A is true but R is false","Both true, R explains A","Both true, R does not explain A","A is false, R is true"],ans:1,exp:"Both statements are true. Low financial literacy in rural areas directly explains why stronger programs are needed. R correctly explains A."},
  {q:"Blood relation: X is Y's father. Z is X's only sibling. Z is female. Z is Y's:",opts:["Aunt","Uncle","Mother","Grandmother"],ans:0,exp:"X = Y's father. Z = X's only sibling = female. X is male, Z is female sibling = Z is Y's paternal aunt."},
  {q:"Coding: If EXAM = 5×1×13 in a code, what is BANK?",opts:["2×1×14×11","2×1×14×10","3×2×15×12","1×2×14×11"],ans:0,exp:"E=5, X=24, A=1, M=13. Position: E=5, A=1, M=13. So BANK: B=2, A=1, N=14, K=11 → 2×1×14×11."},
  {q:"Logical sequence: Arrange in proper order: (1)Analysis (2)Problem definition (3)Solution implementation (4)Data collection (5)Conclusion",opts:["2,4,1,3,5","2,1,4,3,5","1,2,4,5,3","2,4,3,1,5"],ans:0,exp:"Logical problem-solving: Define problem → Collect data → Analyze → Implement solution → Conclude = 2,4,1,3,5."},
  {q:"Statement: 'All that glitters is not gold.' Best interpretation?",opts:["Gold never glitters","Appearances can be deceptive","Only gold glitters","All glittering things are valuable"],ans:1,exp:"This proverb means not everything that appears attractive or valuable actually is. Appearances can deceive — core message."}
],

"sbi-quant": [
  {q:"P(at least one head in 3 coin tosses)?",opts:["1/8","3/8","7/8","5/8"],ans:2,exp:"P(at least one) = 1 − P(none) = 1 − (1/2)³ = 1 − 1/8 = 7/8."},
  {q:"In how many ways can 5 people sit in a circular arrangement?",opts:["120","24","60","20"],ans:1,exp:"Circular = (n−1)! = 4! = 24."},
  {q:"A bag has 4 red, 3 blue, 2 green. P(not blue)?",opts:["1/3","2/3","3/9","4/9"],ans:1,exp:"P(not blue) = 6/9 = 2/3. Or: 1 − P(blue) = 1 − 3/9 = 6/9."},
  {q:"Mix 20L milk (₹40/L) with 5L water (₹0/L). Cost of mixture per litre?",opts:["₹30","₹32","₹36","₹40"],ans:1,exp:"Total cost = 20×40 = ₹800. Total volume = 25L. Cost/L = 800/25 = ₹32."},
  {q:"Area of circle with circumference 44cm (π=22/7)?",opts:["144 cm²","154 cm²","164 cm²","174 cm²"],ans:1,exp:"2πr=44 → r=7. Area = πr² = 22/7 × 49 = 154 cm²."},
  {q:"Volume of cube with surface area 96 cm²?",opts:["32 cm³","48 cm³","64 cm³","56 cm³"],ans:2,exp:"6a² = 96 → a² = 16 → a = 4. Volume = 4³ = 64 cm³."},
  {q:"₹5000 at 8% CI for 2 years. Amount after 2 years?",opts:["₹5800","₹5832","₹5920","₹5780"],ans:1,exp:"A = 5000 × (1.08)² = 5000 × 1.1664 = ₹5832."},
  {q:"Alligation: Mix milk at ₹50/L and ₹30/L to get ₹40/L. Ratio?",opts:["1:1","1:2","2:1","3:1"],ans:0,exp:"Alligation: (50-40):(40-30) = 10:10 = 1:1. Equal quantities of both."},
  {q:"Quadratic: x² − 7x + 12 = 0. Values of x?",opts:["3 and 4","2 and 6","1 and 12","3 and -4"],ans:0,exp:"(x−3)(x−4)=0. x=3 or x=4."},
  {q:"5 books on shelf — how many ways to arrange 3 specific books out of 5?",opts:["6","10","20","60"],ans:3,exp:"5P3 = 5!/(5-3)! = 5×4×3 = 60. Order matters (arrangement) → Permutation."},
  {q:"Distance A to B = 240km. Speeds 60 and 80 km/h toward each other. Time to meet?",opts:["1.2 hrs","1.5 hrs","1.71 hrs","2 hrs"],ans:2,exp:"Time = 240/(60+80) = 240/140 = 12/7 ≈ 1.71 hours."},
  {q:"P(sum=7 when two dice thrown)?",opts:["1/6","5/36","6/36","7/36"],ans:2,exp:"Favourable: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) = 6 outcomes. Total = 36. P = 6/36 = 1/6."},
  {q:"Perimeter of rectangle = 60cm. Length = twice breadth. Area?",opts:["150 cm²","180 cm²","200 cm²","220 cm²"],ans:2,exp:"2(l+b)=60 → l+b=30. l=2b → 3b=30 → b=10, l=20. Area=200 cm²."},
  {q:"How many ways to select a committee of 3 from 8 people?",opts:["24","56","120","336"],ans:1,exp:"8C3 = 8!/(3!×5!) = 56. Order doesn't matter → Combination."},
  {q:"Lateral surface area of cylinder with radius 7cm, height 10cm (π=22/7)?",opts:["440 cm²","480 cm²","520 cm²","560 cm²"],ans:0,exp:"LSA = 2πrh = 2 × 22/7 × 7 × 10 = 440 cm²."},
  {q:"Speed of train = 90 km/h. Time to cross a 150m platform if train is 100m long?",opts:["8 sec","10 sec","12 sec","15 sec"],ans:2,exp:"Distance = 150+100 = 250m. Speed = 90km/h = 25 m/s. Time = 250/25 = 10 sec."},
  {q:"Two cards drawn from pack of 52. P(both aces)?",opts:["1/221","1/169","2/221","1/26"],ans:0,exp:"P = C(4,2)/C(52,2) = 6/1326 = 1/221."},
  {q:"Volume of cone with radius 6cm and height 14cm (π=22/7)?",opts:["528 cm³","616 cm³","528 cm³","792 cm³"],ans:0,exp:"V = (1/3)πr²h = (1/3) × 22/7 × 36 × 14 = 528 cm³."},
  {q:"A sum becomes 4 times in 12 years at SI. Rate of interest?",opts:["20%","25%","30%","33.3%"],ans:1,exp:"4 times → 300% gain in 12 years. Rate = 300/12 = 25% pa."},
  {q:"Probability: From letters of 'EXAM', if one letter picked randomly, P(vowel)?",opts:["1/4","1/2","3/4","2/3"],ans:1,exp:"EXAM has letters E, X, A, M. Vowels = E, A = 2 vowels. P = 2/4 = 1/2."}
],

// ===== UGC NET PAPER 1 QUESTIONS =====

"ugcp1-teaching": [
  {q:"Which level of teaching emphasizes problem-solving and critical thinking as its highest goal?",opts:["Memory level","Understanding level","Reflective level","Demonstration level"],ans:2,exp:"Reflective Level (Morrison's) is the highest — involves critical analysis, creative problem-solving, and evaluation."},
  {q:"Formative evaluation is conducted:",opts:["At end of year","During the learning process to improve it","Before teaching begins","For certification only"],ans:1,exp:"Formative evaluation is ongoing, during instruction. Its purpose is to monitor progress and provide feedback to improve learning."},
  {q:"Which teaching method involves learners enacting realistic scenarios?",opts:["Lecture method","Simulation / Role Play","Discussion method","Project method"],ans:1,exp:"Simulation and Role Play involve learners acting out real-life situations to develop practical and professional skills."},
  {q:"Norm-referenced evaluation compares a student's performance with:",opts:["A fixed standard","Their own previous performance","Other students in the group","The teacher's expectations"],ans:2,exp:"Norm-referenced = comparing performance to a reference group (other students). Criterion-referenced = comparing to a fixed standard."},
  {q:"Bloom's Taxonomy REVISED (2001) — highest cognitive level?",opts:["Evaluation","Synthesis","Create","Application"],ans:2,exp:"Revised Bloom's (2001): Remember→Understand→Apply→Analyze→Evaluate→CREATE (highest). Original (1956): highest = Evaluation."},
  {q:"Diagnostic evaluation is conducted:",opts:["At the end of the course","During instruction","Before instruction begins","During final exams"],ans:2,exp:"Diagnostic evaluation = BEFORE teaching, to identify prior knowledge, strengths, and weaknesses to plan teaching accordingly."},
  {q:"The Flipped Classroom model means:",opts:["Students teach each other","Content at home (videos), activities in class","Teacher lectures only online","No formal teaching at all"],ans:1,exp:"Flipped Classroom: traditional 'homework' and 'lecture' are reversed. Content delivery at home via videos; class time for activities and discussion."},
  {q:"Team Teaching involves:",opts:["Students teaching each other","Two or more teachers co-planning and co-delivering to same group","Teacher using multiple methods","Online teaching only"],ans:1,exp:"Team teaching = two or more teachers jointly plan, teach, and evaluate the same student group, combining their expertise."},
  {q:"Which is the LOWEST level of teaching?",opts:["Reflective level","Understanding level","Memory level","Application level"],ans:2,exp:"Memory Level (Herbartian) is lowest — involves rote learning and recall of facts without critical thinking."},
  {q:"Criterion-referenced evaluation measures:",opts:["Student's rank in class","Performance against a predetermined standard","Comparison with peer group","Teacher's subjective judgment"],ans:1,exp:"Criterion-referenced = measures whether a student has met a specific criterion/standard (e.g., pass marks of 50%). Not compared to others."},
  {q:"Teaching is described as 'tri-polar' because it involves:",opts:["Three teaching methods","Teacher, Learner, and Curriculum","Three levels of Bloom's Taxonomy","Three evaluation types"],ans:1,exp:"Teaching is tri-polar: involves interaction between the Teacher, the Learner, and the Curriculum/Content — all three are essential."},
  {q:"Programmed Learning is based on which psychologist's work?",opts:["Piaget","Vygotsky","B.F. Skinner","Bruner"],ans:2,exp:"Programmed Learning is based on B.F. Skinner's operant conditioning and behaviorism — immediate reinforcement after each correct response."},
  {q:"'Summative evaluation' is best described as:",opts:["Ongoing feedback during learning","End-of-course evaluation for certification/grading","Pre-teaching diagnostic","Peer evaluation"],ans:1,exp:"Summative = at the END of a course/unit. Judges overall achievement. Used for grading and certification (e.g., final exams, board exams)."},
  {q:"Which teaching method is BEST for developing critical thinking?",opts:["Lecture method","Rote learning","Discussion method","Drill and practice"],ans:2,exp:"Discussion method requires students to analyze, question, defend positions, and consider alternatives — directly develops critical thinking."},
  {q:"Project Method is best for:",opts:["Introducing a new concept quickly","Large lecture halls","Developing creativity, application, and real-world problem solving","Testing memorization"],ans:2,exp:"Project Method (Kilpatrick): students work on real-world projects over time. Best for application, creativity, collaboration, and problem-solving."}
],

"ugcp1-research": [
  {q:"A researcher studies cancer survivors through in-depth interviews. This is:",opts:["Experimental research","Quantitative research","Qualitative research","Historical research"],ans:2,exp:"Qualitative research uses non-numerical, experiential data (interviews, narratives). Focuses on meanings and perceptions."},
  {q:"Accepting a false null hypothesis is called:",opts:["Type I error","Type II error","Sampling error","Random error"],ans:1,exp:"Type II error (β error) = accepting false H₀ (missing the real effect). Type I error (α) = rejecting true H₀ (false alarm)."},
  {q:"Snowball sampling is MOST appropriate for:",opts:["Large representative samples","Hard-to-reach populations","Random national surveys","School children"],ans:1,exp:"Snowball = existing participants recruit new ones. Ideal for hard-to-reach groups (drug users, rare diseases, sensitive topics)."},
  {q:"The independent variable in an experiment is the variable that is:",opts:["Measured as the outcome","Deliberately manipulated by the researcher","Kept constant throughout","Observed passively"],ans:1,exp:"Independent variable = the one deliberately changed/manipulated by the researcher. Dependent variable = what is measured as result."},
  {q:"Action research is PRIMARILY conducted to:",opts:["Publish in international journals","Solve immediate practical problems in one's own setting","Contribute to general theory","Fulfill PhD requirements"],ans:1,exp:"Action research = practitioners (teachers, managers) study and solve immediate problems in their own work context. Practical, immediate."},
  {q:"What is plagiarism in research?",opts:["Citing too many sources","Using others' work without proper attribution","Writing too many papers","Repeating own previous work without citation"],ans:1,exp:"Plagiarism = presenting someone else's ideas, data, writing, or work as your own without proper acknowledgment/citation."},
  {q:"Stratified random sampling ensures:",opts:["Equal numbers from all groups","Proportional representation of subgroups","Only volunteers are included","Researchers choose participants"],ans:1,exp:"Stratified sampling: population divided into strata, random samples taken from each stratum in proportion to size. Ensures representation."},
  {q:"Deductive reasoning in research goes from:",opts:["Specific observations to general theory","General theory to specific hypothesis to test","Data collection to conclusion","Observations to inferences"],ans:1,exp:"Deductive = top-down: General theory → form specific hypothesis → test it → confirm/refute. Inductive = bottom-up (specific → general)."},
  {q:"Reliability of a research instrument refers to:",opts:["Whether it measures what it claims","Consistency of results under same conditions repeatedly","How many subjects were tested","Whether findings can be generalized"],ans:1,exp:"Reliability = consistency and stability of measurement. Validity = accuracy (measuring what it claims to measure). Both are needed."},
  {q:"Which is NOT a primary source of data?",opts:["Questionnaire filled by respondents","Direct observation by researcher","Published research paper","Personal interviews"],ans:2,exp:"Published research papers are SECONDARY sources (someone else collected and analyzed the data). Primary = original, first-hand data collection."},
  {q:"Double-blind study means:",opts:["Both researchers are visually impaired","Neither participants NOR researchers know who received treatment/placebo","Only participants are unaware","No control group"],ans:1,exp:"Double-blind: eliminates both participant and researcher bias — neither knows which group received real treatment vs placebo."},
  {q:"'Operationalizing a variable' means:",opts:["Giving a variable an abstract definition","Defining a variable in specific, measurable terms","Choosing the right statistical test","Selecting sample size"],ans:1,exp:"Operationalization = defining a variable in concrete, measurable, observable terms so it can be studied empirically."},
  {q:"Literature review in research primarily serves to:",opts:["Replace methodology","Identify gaps in existing knowledge and situate the study","Prove the hypothesis","Summarize collected data"],ans:1,exp:"Literature review: identifies what is already known, reveals gaps, and contextualizes the new study within existing knowledge."},
  {q:"Research hypothesis must be:",opts:["Complex and multi-dimensional","Testable and falsifiable","Proven before the study begins","Stated after data collection"],ans:1,exp:"A good hypothesis must be: testable (can be empirically examined) and falsifiable (can potentially be proven wrong)."},
  {q:"Cluster sampling is most cost-effective when:",opts:["Population is homogeneous","Population is naturally grouped and geographically spread","A precise representative sample is needed","Population is very small"]  ,ans:1,exp:"Cluster sampling works best when population is naturally divided into groups (villages, schools) spread geographically — saves travel costs."}
],

"ugcp1-ict": [
  {q:"SWAYAM platform was launched by which ministry?",opts:["Ministry of IT","Ministry of Education","Ministry of Finance","Ministry of Science"],ans:1,exp:"SWAYAM (Study Webs of Active Learning for Young Aspiring Minds) = launched by Ministry of Education. India's national MOOC platform."},
  {q:"NPTEL courses are offered by:",opts:["IGNOU","UGC","IITs and IISc jointly","All central universities"],ans:2,exp:"NPTEL = National Programme on Technology Enhanced Learning. Offered jointly by IITs and IISc Bangalore."},
  {q:"In a flipped classroom, class time is used for:",opts:["Lecture delivery","Note-taking from teacher","Hands-on activities, discussions, problem-solving","Watching recorded videos"],ans:2,exp:"Flipped: content at home, class for activities. Class time = interactive, applied learning with teacher guidance."},
  {q:"DIKSHA platform is used for:",opts:["Higher education MOOCs","School-level digital educational content (K-12)","Professional corporate training","Research publications"],ans:1,exp:"DIKSHA = Digital Infrastructure for Knowledge Sharing. National platform for school education digital content (textbooks, worksheets, videos)."},
  {q:"Shodhganga is a repository of:",opts:["School textbooks","Indian PhD theses and dissertations","Government reports","International journals"],ans:1,exp:"Shodhganga = INFLIBNET's open-access repository of Indian PhD theses and dissertations from universities across India."},
  {q:"LMS stands for:",opts:["Library Management System","Learning Management System","Local Media Server","Language Monitoring Software"],ans:1,exp:"LMS = Learning Management System (Moodle, Blackboard, Canvas). Software for creating, delivering, and managing e-learning courses."},
  {q:"Synchronous e-learning means:",opts:["Self-paced any time","Real-time learning with simultaneous interaction","Recorded video only","Correspondence-based learning"],ans:1,exp:"Synchronous = same time. Live online classes, video conferencing, real-time chat. Asynchronous = different times (recorded, forums)."},
  {q:"INFLIBNET stands for:",opts:["International Library Network","Information and Library Network","India's Library for New Books","Integrated Library Network"],ans:1,exp:"INFLIBNET = Information and Library Network. Provides networked information and library services to universities under UGC."},
  {q:"Blended learning is BEST described as:",opts:["100% online learning","100% face-to-face learning","Combination of online digital + face-to-face instruction","Learning through mobile phones only"],ans:2,exp:"Blended learning = hybrid approach combining online digital content delivery with traditional face-to-face classroom instruction."},
  {q:"MOOC stands for:",opts:["Modern Online Open Course","Massive Open Online Course","Multiple Object Oriented Course","Managed Online Open Curriculum"],ans:1,exp:"MOOC = Massive Open Online Course. Large-scale online learning open to anyone globally with no enrollment limit."},
  {q:"e-PG Pathshala provides content for which level?",opts:["School (K-12)","Undergraduate level","Postgraduate level","Doctoral research"],ans:2,exp:"e-PG Pathshala = e-content portal specifically designed for postgraduate students across subjects under UGC initiative."},
  {q:"Which protocol is used to SEND emails?",opts:["POP3","IMAP","SMTP","HTTP"],ans:2,exp:"SMTP = Simple Mail Transfer Protocol. Used for SENDING emails. POP3 and IMAP are used for RECEIVING/accessing emails."},
  {q:"Virtual Labs allow students to:",opts:["Attend physical labs remotely","Perform laboratory experiments through simulation/remote access","Only watch lab demonstrations","Skip laboratory work entirely"],ans:1,exp:"Virtual Labs = web-based platforms that simulate or provide remote access to laboratory experiments, especially for science and engineering students."},
  {q:"VIDYA-DAAN scheme is for:",opts:["Student scholarships","Crowdsourcing digital educational content from educators","Free device distribution","Teacher salaries"],ans:1,exp:"VIDYA-DAAN = platform for educators and institutions to voluntarily contribute digital educational content for sharing."},
  {q:"Internet and World Wide Web are:",opts:["The same thing","Different — Internet is the network; WWW is a service on it","WWW is bigger than Internet","Internet only works through WWW"],ans:1,exp:"Internet = the global network infrastructure (hardware, cables, protocols). WWW = a SERVICE running on the internet (websites accessed via HTTP)."}
],

"ugcp1-logic": [
  {q:"In Nyaya inference, 'Vyāpti' refers to:",opts:["The subject of inference","Universal concomitance between sign and signified","The conclusion of argument","Direct perception"],ans:1,exp:"Vyāpti = universal invariable concomitance. 'Wherever smoke, there fire.' Foundation of Anumāna (inference). Without Vyāpti, no valid inference."},
  {q:"Which Pramāna involves gaining knowledge through reliable verbal testimony?",opts:["Pratyaksha","Anumāna","Upamāna","Shabda/Āgama"],ans:3,exp:"Shabda Pramāna (also called Āgama) = knowledge from trustworthy verbal testimony/authority. One of the 4 Pramānas in Nyaya."},
  {q:"First step in Nyaya's 5-step syllogism (Pañcāvayava) is:",opts:["Hetu","Udāharana","Pratijña","Upanaya"],ans:2,exp:"Pratijña = the Proposition/Claim. First step: state what is to be proved. 'The hill has fire.'"},
  {q:"Nyaya school recognizes how many Pramānas (valid sources of knowledge)?",opts:["2","3","4","5"],ans:2,exp:"Nyaya = 4 Pramānas: Pratyaksha (perception), Anumāna (inference), Upamāna (comparison), Shabda (testimony)."},
  {q:"Valid syllogism: All M are P. Some S are M. Conclusion?",opts:["All S are P","No S are P","Some S are P","Some S are not P"],ans:2,exp:"AII-1 syllogism: All M are P + Some S are M → Some S are P. Valid inference."},
  {q:"Anumāna in Nyaya philosophy refers to:",opts:["Direct sensory perception","Inference through signs and universal relationship","Verbal testimony","Comparison-based knowledge"],ans:1,exp:"Anumāna = inference. Knowledge derived through reasoning — using a sign (smoke) and the Vyāpti relationship to infer what is not directly perceived (fire)."},
  {q:"'Post hoc ergo propter hoc' logical fallacy means:",opts:["Attacking the person","Concluding causation from correlation/sequence","Using irrelevant evidence","Overgeneralizing"],ans:1,exp:"Post hoc ergo propter hoc = 'after this, therefore because of this.' Fallacy of assuming that because B followed A, A caused B."},
  {q:"In Nyaya, 'Paksha' refers to:",opts:["The major term to be proved","The subject/locus where property is inferred","The universal relationship","The example"],ans:1,exp:"Paksha = the subject about which inference is made. Example: 'the hill' in 'the hill has fire (inferred).'"},
  {q:"The 3rd step in Nyaya syllogism (Udāharana) serves to:",opts:["State the proposition","Provide the reason","Give a universal example establishing Vyāpti","Apply the universal to the case"],ans:2,exp:"Udāharana = the universal example that establishes the Vyāpti relationship. 'Wherever there is smoke, there is fire, like in a kitchen.'"},
  {q:"Which is an example of Ad Hominem fallacy?",opts:["Using irrelevant statistics","Attacking the person making the argument instead of the argument","Drawing universal conclusion from one example","False dilemma"],ans:1,exp:"Ad Hominem = attacking the person (their character, credibility) instead of addressing the actual argument or evidence they present."},
  {q:"Inductive reasoning goes from:",opts:["General to specific","Specific observations to general conclusion","Theory to hypothesis","Hypothesis to data"],ans:1,exp:"Inductive reasoning = specific observations/examples → generalize to form a conclusion or theory. Opposite of deductive reasoning."},
  {q:"Valid or Invalid: 'No S are M. All P are M. Therefore, no S are P.'",opts:["Valid","Invalid","Depends on content","Cannot determine"],ans:0,exp:"EAE-2 syllogism: No S are M (No M are S by conversion) + All P are M → No S are P. This is a valid logical form."},
  {q:"'Upamāna' Pramāna in Nyaya is knowledge gained through:",opts:["Perception","Inference","Comparison with a previously known object","Verbal testimony"],ans:2,exp:"Upamāna = comparison/analogy. Knowing an unfamiliar object by comparing it with a familiar one based on described similarity."},
  {q:"Argument: 'Students who study more score higher. Therefore, all top scorers studied more than average.' This commits what error?",opts:["Hasty generalization","Ad hominem","Affirming the consequent","False dilemma"],ans:2,exp:"Affirming the consequent: 'If A then B. B. Therefore A.' Studying more → higher scores. But higher scores → studied more is not necessarily valid."},
  {q:"Venn Diagram: All dogs are animals. All animals are living things. Correctly shows:",opts:["Dogs ∩ Animals = partial overlap","Animals is subset of dogs","Dogs is subset of animals, which is subset of living things","Dogs and animals are equal sets"],ans:2,exp:"Dogs ⊂ Animals ⊂ Living Things. Three concentric circles: innermost = dogs, middle = animals, outermost = living things."}
],

"ugcp1-highered": [
  {q:"NAAC is located at:",opts:["New Delhi","Mumbai","Bengaluru","Chennai"],ans:2,exp:"NAAC (National Assessment and Accreditation Council) headquarters is in Bengaluru, Karnataka. Established 1994 under UGC."},
  {q:"NEP 2020 proposed which school structure?",opts:["10+2","8+4","5+3+3+4","6+4+2"],ans:2,exp:"NEP 2020 introduced 5+3+3+4 replacing the old 10+2. Foundational(5)+Preparatory(3)+Middle(3)+Secondary(4)=15 years."},
  {q:"UGC was established under:",opts:["UGC Act 1951","UGC Act 1956","Education Act 1964","Higher Education Act 1970"],ans:1,exp:"University Grants Commission was established under the UGC Act, 1956."},
  {q:"AICTE regulates which type of institutions?",opts:["Medical colleges","Law colleges","Technical institutions (engineering, management, pharmacy)","General arts and science colleges"],ans:2,exp:"AICTE = All India Council for Technical Education. Regulates technical education: engineering, MBA, MCA, pharmacy, architecture."},
  {q:"NAAC grading — which is the HIGHEST grade?",opts:["A","A+","A++","Excellent"],ans:2,exp:"NAAC grading: A++ (highest) → A+ → A → B++ → B+ → B → C → D (not accredited). Institutions aim for A and above."},
  {q:"NEP 2020's GER target for higher education by 2035?",opts:["30%","40%","50%","60%"],ans:2,exp:"NEP 2020 targets 50% Gross Enrollment Ratio in higher education by 2035 (from current ~28%)."},
  {q:"Academic Bank of Credits (ABC) under NEP 2020 allows:",opts:["Banks to fund education","Students to store and transfer credits across institutions","Annual scholarship deposits","Instant degree awards"],ans:1,exp:"ABC = students can accumulate, store, and transfer credits earned from various higher education institutions across India."},
  {q:"IGNOU is known as:",opts:["India's oldest university","World's largest open university by enrollment","India's top research university","First private university in India"],ans:1,exp:"IGNOU (Indira Gandhi National Open University) = world's largest open university by student enrollment. Established 1985, New Delhi."},
  {q:"NEP 2020's 4-year UG programme allows exit after 1 year with:",opts:["Diploma","Bachelor's Degree","Certificate","No qualification"],ans:2,exp:"4-year UG multiple exit: 1 year = Certificate. 2 years = Diploma. 3 years = Bachelor's Degree. 4 years = Bachelor's with Research/Honours."},
  {q:"'Deemed University' status is granted by:",opts:["State government","Central government on UGC recommendation","AICTE","Ministry directly without UGC"],ans:1,exp:"Deemed University = Central Government grants the status based on UGC's recommendation to institutions of high standard."},
  {q:"Distance education in India is regulated by:",opts:["AICTE","NAAC","UGC (absorbed DEC)","Individual state governments"],ans:2,exp:"UGC (after absorbing the Distance Education Council — DEC) regulates open and distance learning in India."},
  {q:"The 5-year Foundational Stage in NEP 2020 covers which ages?",opts:["3-6 years","3-8 years","5-10 years","6-11 years"],ans:1,exp:"NEP 2020 Foundational Stage = ages 3 to 8 (5 years). Includes 3 years of pre-school (Anganwadi/Balvatika) + Classes 1-2."},
  {q:"NEP 2020 recommends mother tongue as medium of instruction up to at least:",opts:["Grade 3","Grade 5","Grade 8","Grade 10"],ans:1,exp:"NEP 2020: mother tongue/local/regional language as medium of instruction at least up to Grade 5, preferably Grade 8 and beyond."},
  {q:"Purpose of NAAC accreditation is to:",opts:["Provide government grants","Assess and certify quality of higher education institutions","Set university fees","Control student admissions"],ans:1,exp:"NAAC's purpose = assessing and accrediting higher educational institutions to ensure and promote quality in Indian higher education."},
  {q:"NEP 2020 aims to eliminate which type of rigid division?",opts:["Urban-rural schools","Public-private universities","Hard separation of curricular, co-curricular, and vocational streams","Small and large classes"],ans:2,exp:"NEP 2020 aims to remove hard separations between academic/curricular, co-curricular/extracurricular, and vocational/professional streams."}
]

};

// Shuffle helper
function shuffleArray(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function getTopicQuestions(topicId, count = 20) {
  const bank = QUESTION_BANKS[topicId];
  if (!bank || bank.length === 0) return [];
  return shuffleArray(bank).slice(0, Math.min(count, bank.length));
}

function getMockQuestions(examKey, count) {
  // Gather all questions for this exam
  const exam = EXAMS[examKey];
  if (!exam) return [];
  let all = [];
  exam.topics.forEach(t => {
    const qs = QUESTION_BANKS[t.id] || [];
    all = all.concat(qs);
  });
  if (all.length === 0) return [];
  return shuffleArray(all).slice(0, Math.min(count, all.length));
}
